[pytest]
addopts = -v --tb=short --strict-markers
testpaths = tests
markers =
    smoke: Smoke tests
    users: Tests related to users endpoint
    products: Tests related to products endpoint
    auth: Tests related to authentication